// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521042403_Migration-2023-05-21-01-23-59")]
    partial class Migration20230521012359
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("TechnicalInformation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("technical_information");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 518, DateTimeKind.Utc).AddTicks(998),
                            Description = "Ut labore quidem consequatur reprehenderit. Sapiente rerum nihil a consequatur iusto et ex. Ut omnis fugiat eligendi distinctio voluptatem omnis ad est.",
                            Name = "Porro voluptatibus deserunt quia quas aut aut doloremque rerum commodi. Nam hic placeat quas quia atque dolore harum est consequuntur. Deleniti sint eum possimus omnis et sit quo tempore hic.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 14m,
                            TechnicalInformation = "Et officiis necessitatibus autem in corrupti omnis perspiciatis harum ut. Non aut quia nobis at animi dolor omnis nostrum. Corrupti dolores deleniti omnis harum nesciunt. Voluptate odio est nam sapiente maiores. Quod eaque animi ut ex alias velit iusto occaecati. Quos qui sint voluptas eos nihil quae corporis reiciendis. Assumenda ipsa velit illo voluptatem modi eius velit assumenda. Magni natus sed eum quis est fugiat velit dolor sit. Adipisci rem voluptatibus eos. Consequuntur consequatur culpa sunt nostrum ullam non optio sit voluptatem. Sint et reprehenderit doloremque veniam sunt molestiae qui dolorum.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 518, DateTimeKind.Utc).AddTicks(999),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 9,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 519, DateTimeKind.Utc).AddTicks(127),
                            Description = "Totam repellat dicta et neque.",
                            Name = "Quo porro sequi corrupti cumque quasi qui et sed sunt. Unde nam omnis non assumenda fugit repudiandae esse.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 13m,
                            TechnicalInformation = "Iure fuga illum quia fugit et. Consequatur eveniet enim consequatur fugiat error. Aut aperiam quidem rerum. Eaque id sint totam optio sed ut eum nostrum. Quos cupiditate necessitatibus quia corrupti in. Nulla magnam nostrum laborum enim aut ab. Alias eveniet qui velit et occaecati in non cupiditate. Qui molestiae quidem non et officia consequuntur qui neque recusandae. Id officia modi explicabo nobis autem veritatis iusto dolorem. Harum modi officiis iusto ut quibusdam error. Excepturi odio voluptatem odio voluptatem eum officia non accusamus.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 519, DateTimeKind.Utc).AddTicks(127),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 520, DateTimeKind.Utc).AddTicks(1002),
                            Description = "Neque ullam officia ut reiciendis autem est. In ut nihil perferendis perferendis id omnis architecto aut enim.",
                            Name = "Voluptatum iusto dolores facilis accusantium nostrum non esse. At ullam qui distinctio praesentium ut et consequuntur maxime. Aut nulla dolores vitae.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 12m,
                            TechnicalInformation = "Inventore nobis maiores facere consequatur nihil consequuntur laudantium nesciunt aut. Nostrum enim quis voluptate eius quaerat ut quis et. Sunt ullam optio est eum laboriosam exercitationem tenetur hic aspernatur. Sapiente libero nostrum ea sunt. Soluta exercitationem optio ut voluptas. Iure voluptatem occaecati consectetur. Aperiam occaecati qui commodi unde quia et voluptatem qui nihil. Tenetur qui maiores eos voluptas quia consequatur aut a officia. Minus est deserunt occaecati non. Omnis ea eaque voluptates quia. Occaecati et possimus placeat error omnis nihil et. Amet consectetur saepe saepe ipsam.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 520, DateTimeKind.Utc).AddTicks(1003),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 521, DateTimeKind.Utc).AddTicks(1317),
                            Description = "Cumque rerum nesciunt dolor nemo animi velit reprehenderit quo odio. Consequatur modi molestiae dolore soluta. Cum repellendus illo explicabo laboriosam sunt.",
                            Name = "Voluptas quo nihil debitis rerum inventore et. Quae qui culpa nobis magni. Ipsam rerum molestiae corrupti quo eaque distinctio.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 11m,
                            TechnicalInformation = "Voluptatem qui nihil et eos et est aspernatur et nemo. Dolores officiis et architecto sit ut ad architecto error. Labore voluptatem sequi deserunt accusantium eos iure. Veniam culpa qui dolorum. Et vel illo repellendus voluptates provident iste tempore sed quo. Facere ratione quia eveniet exercitationem. Cupiditate vel voluptates consequuntur aut et in assumenda. Minus sapiente quae commodi eveniet dolor voluptatem dicta. Saepe aut autem quam et est consequatur sed libero. Quia sequi voluptate qui voluptates aperiam et necessitatibus odio.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 521, DateTimeKind.Utc).AddTicks(1317),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 4,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 521, DateTimeKind.Utc).AddTicks(8559),
                            Description = "Repellendus expedita dicta qui excepturi rerum minus.",
                            Name = "Sint quis neque voluptate eum corporis nisi vero ipsam.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 12m,
                            TechnicalInformation = "Aliquid delectus odio eum consequuntur. Dolor temporibus qui sed. Ut perferendis sit ut. Alias dolores et consequuntur aperiam quam quam suscipit ut ea. Ea dignissimos velit qui nesciunt quia odio. Et soluta iusto nihil corporis cumque. Totam corrupti corporis numquam totam. Aperiam totam ad et sequi explicabo amet nemo. Molestiae id ex accusantium. Modi praesentium consequatur eligendi fugiat et. Voluptatem natus provident totam sint id consectetur.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 521, DateTimeKind.Utc).AddTicks(8559),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 10,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 522, DateTimeKind.Utc).AddTicks(9275),
                            Description = "Ea ipsum repellat labore animi explicabo quo porro recusandae sunt. Dolorem commodi dolor consequuntur tenetur excepturi nihil dignissimos sequi id.",
                            Name = "Pariatur hic corrupti sit.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 11m,
                            TechnicalInformation = "Necessitatibus occaecati et quia ea eum esse error et soluta. Sed est magnam aliquam sunt quia possimus aperiam occaecati. Et veritatis consequatur vel et dicta. Reiciendis culpa et quibusdam odio saepe. Quibusdam voluptatem est vitae adipisci temporibus expedita ut optio molestias. Culpa dolores eius recusandae sit quos. Ad enim ut sint. Omnis voluptas sint a earum. Repellendus saepe repudiandae ut est veritatis commodi aspernatur quod voluptas. Doloribus quis laudantium ullam sed non dolore facere reprehenderit molestiae. Rerum id eaque et voluptas sint inventore aspernatur accusantium. Soluta nam quidem aut. Eligendi consequuntur hic repellat iure aut ea sunt voluptas qui.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 522, DateTimeKind.Utc).AddTicks(9276),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 9,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 524, DateTimeKind.Utc).AddTicks(1811),
                            Description = "Ipsum vel veniam reiciendis iure nisi aut repudiandae autem. Nemo aliquid omnis inventore voluptatem dignissimos quia porro consequatur quia. Blanditiis et aut necessitatibus et. Quis enim neque deserunt.",
                            Name = "Quis consequuntur eius autem ut voluptas distinctio. Hic nemo tempore qui maiores sapiente quod.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 19m,
                            TechnicalInformation = "Quia tempore doloribus iusto animi at neque. Molestias quaerat est consectetur ullam qui sint magnam neque aut. Fugit sit beatae omnis. Ut enim inventore molestiae vel quam dolor sed qui ducimus. Temporibus dignissimos rerum aut qui esse. Qui quaerat at et error. Aut ad illo rerum ipsa reiciendis modi nulla odio commodi. Quis excepturi quia temporibus cupiditate eveniet. Totam eius sunt reprehenderit accusamus recusandae qui et. Quo voluptatem aut molestias quia et ipsa in eveniet aperiam. Repellendus incidunt non enim commodi sit quo vitae illo. Iusto doloremque aut veniam libero. Omnis et dolor sapiente odio error.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 524, DateTimeKind.Utc).AddTicks(1811),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 6,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 525, DateTimeKind.Utc).AddTicks(4004),
                            Description = "Eum omnis animi reprehenderit impedit necessitatibus molestias optio autem omnis. Earum nihil repellendus ut velit quae aut quo quam. Fugit omnis amet saepe necessitatibus quo.",
                            Name = "Non omnis incidunt ipsum temporibus facere cum molestiae quia. Qui ut at aut atque voluptatum non rerum accusantium. Quia accusantium ratione dolores iure.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 14m,
                            TechnicalInformation = "Blanditiis libero dolorem omnis nihil atque vitae quibusdam harum sapiente. Enim aut occaecati voluptates voluptate velit consequatur sit laborum magni. Magni voluptas blanditiis deserunt. Illum velit non harum atque dolor velit ut distinctio. At sed vel ut labore. Optio voluptatem sed mollitia quidem sequi repellendus. Fugiat sed dolorum et voluptates ducimus quas. Consectetur nobis et dolores doloremque alias sint. Modi similique et excepturi impedit totam quia est suscipit voluptatem. Fuga tempore repudiandae saepe. Omnis dolores dolorum molestiae similique. Voluptates qui est velit voluptatum harum.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 525, DateTimeKind.Utc).AddTicks(4004),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 526, DateTimeKind.Utc).AddTicks(3426),
                            Description = "Quaerat nemo magni iste suscipit.",
                            Name = "Esse sunt repudiandae esse aut non. Non debitis ullam incidunt dolores molestias hic voluptates eaque enim. Consequatur rerum tempore incidunt maiores aut quaerat sed. Est non qui voluptas.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 10m,
                            TechnicalInformation = "Et est aut voluptates et voluptatem laborum ut consectetur. Ipsam incidunt reprehenderit culpa dolor. Suscipit eveniet unde adipisci nobis quos modi possimus. Consequatur cum non rem debitis eius. Assumenda provident dolore sit temporibus. Consequatur aperiam minima libero aut. Sit ea alias voluptas eos. Ea tempore officia iure odit magnam aliquid voluptates dicta atque. Eius blanditiis et qui suscipit distinctio vero laborum aliquid. Id numquam necessitatibus eum atque delectus sapiente culpa aliquam.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 526, DateTimeKind.Utc).AddTicks(3426),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 3,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 527, DateTimeKind.Utc).AddTicks(5513),
                            Description = "Sint quis quibusdam recusandae sed et facilis repellat at. Voluptas omnis rerum fugit omnis sed et nihil.",
                            Name = "Voluptas harum dolores architecto quis autem. Sunt molestias dignissimos unde praesentium similique. Beatae sint ex eos nulla rerum corporis nesciunt id. Expedita minus et ut repellendus voluptatem et.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 15m,
                            TechnicalInformation = "Quo ut deleniti id nostrum a eaque sequi voluptatum porro. Velit aspernatur amet laboriosam est et earum. Optio dicta velit laborum et nam sapiente qui sapiente. Eius quia autem veritatis aut numquam repellendus consequatur. Assumenda nihil alias nulla consequuntur est ratione corrupti architecto natus. Provident mollitia rerum nostrum enim sit occaecati. Aliquam assumenda iste minus quos quia quia vel quam. Et quaerat rem molestias officia. Quis similique aut nobis et reprehenderit est. Voluptatem facere omnis eum est doloribus fugiat et. Et quod omnis rerum quisquam.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 527, DateTimeKind.Utc).AddTicks(5514),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1954, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(470),
                            Email = "idell@fadel.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "bryon",
                            Name = "Mossie",
                            Password = "Doloribus ut id facere et ab.",
                            Phone = "4149297509",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Towne",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(471)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1924, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(5304),
                            Email = "rita.ruecker@mccullough.co.uk",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "graham",
                            Name = "Cecile",
                            Password = "Neque consectetur fugit similique nihil et nihil et magnam repellat. Neque officiis officiis et.",
                            Phone = "7834931970",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Blick",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(5305)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1913, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(9460),
                            Email = "houston_hyatt@leannon.co.uk",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "wiley",
                            Name = "Amina",
                            Password = "Cum eveniet dolorem ab tempore commodi et est.",
                            Phone = "0768136148",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Corwin",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 512, DateTimeKind.Utc).AddTicks(9460)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1940, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 513, DateTimeKind.Utc).AddTicks(4289),
                            Email = "cara@leannon.name",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "amir",
                            Name = "Destiney",
                            Password = "Aut repudiandae aliquam occaecati. Praesentium dolor libero a qui voluptas et.",
                            Phone = "5360938382",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Lehner",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 513, DateTimeKind.Utc).AddTicks(4290)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1933, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(232),
                            Email = "magdalen@dietrich.uk",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "charlene.blanda",
                            Name = "Ciara",
                            Password = "Omnis qui iure illo quo quos quia. Excepturi ut maxime qui unde a odio rerum aut. Inventore quis soluta sint ea consectetur quam laudantium.",
                            Phone = "9327830512",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Mohr",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(233)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1902, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(5048),
                            Email = "alysson@leuschke.co.uk",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "torey",
                            Name = "Moses",
                            Password = "Aspernatur excepturi aut expedita. Et et dolores et quibusdam.",
                            Phone = "2962191363",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Wintheiser",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(5048)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2018, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(9977),
                            Email = "everardo.steuber@blanda.co.uk",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "mallie",
                            Name = "Dean",
                            Password = "Cumque voluptates delectus ea sequi soluta. Voluptates earum neque perferendis voluptatem cum cumque.",
                            Phone = "1931092036",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Spencer",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 514, DateTimeKind.Utc).AddTicks(9977)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1903, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 515, DateTimeKind.Utc).AddTicks(6305),
                            Email = "doyle.cremin@kassulke.biz",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "buddy",
                            Name = "Alfredo",
                            Password = "Et autem est impedit tempora aspernatur. Exercitationem occaecati et expedita veniam fugiat in voluptas occaecati. Dolores deleniti unde saepe dignissimos dolor blanditiis voluptatem. Impedit voluptas id odit.",
                            Phone = "4833079151",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Luettgen",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 515, DateTimeKind.Utc).AddTicks(6305)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1967, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 516, DateTimeKind.Utc).AddTicks(1775),
                            Email = "rollin_cole@oharalubowitz.biz",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "olaf",
                            Name = "Mallory",
                            Password = "Cum est qui dignissimos repellendus beatae qui dolore. Cumque sed sed nesciunt veritatis vero ullam.",
                            Phone = "4490828977",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Fritsch",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 516, DateTimeKind.Utc).AddTicks(1775)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1938, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 516, DateTimeKind.Utc).AddTicks(6768),
                            Email = "ralph.oberbrunner@spenceroconner.ca",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "watson_mayer",
                            Name = "Jayda",
                            Password = "Totam et deleniti consectetur magni rerum. Libero perferendis voluptatem magni.",
                            Phone = "8271100459",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Labadie",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 24, 3, 516, DateTimeKind.Utc).AddTicks(6769)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
