// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521045716_Migration-2023-05-21-01-57-12")]
    partial class Migration20230521015712
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("TechnicalInformation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("technical_information");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 177, DateTimeKind.Utc).AddTicks(8278),
                            Description = "Blanditiis voluptatem dolores rerum maiores veritatis. Porro aut ut maxime quaerat veritatis et voluptatem.",
                            Name = "Rerum fugit ullam asperiores ut molestiae amet. Vitae aliquid ea cumque voluptatem atque repellat est rerum. Sed qui facilis consequuntur. Repellat voluptas sit ea vero pariatur rerum vel.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 20m,
                            TechnicalInformation = "Consequatur quia maiores velit impedit quod eos repellat. Ipsam placeat non pariatur nostrum molestias placeat. Cum autem enim voluptatem minima ducimus incidunt. Harum vel fugiat sequi eum expedita voluptatem tenetur est. Facilis enim in nostrum et iusto et quia et repellat. Quisquam nihil eum illo deleniti animi. Est cupiditate dicta porro quidem et vel quia. Dolores in perspiciatis esse quia. Eligendi corporis sit cupiditate. Molestias est repellendus nihil perspiciatis eum aperiam. Ipsum exercitationem ex officiis sit.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 177, DateTimeKind.Utc).AddTicks(8279),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 178, DateTimeKind.Utc).AddTicks(5082),
                            Description = "Adipisci qui eos qui enim delectus. Ut vitae porro totam reprehenderit nulla. In et facilis qui dolor enim sit.",
                            Name = "Voluptas architecto consequatur modi asperiores corporis.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 20m,
                            TechnicalInformation = "Quae rerum fugit adipisci. Autem consequatur enim qui id libero. Adipisci est ut laboriosam. Non rerum saepe nesciunt nihil. Accusamus omnis cumque facilis occaecati officia esse vero qui. Fugiat natus aut officia blanditiis. Enim molestias dicta qui voluptatum amet veniam culpa vitae qui. Est recusandae hic culpa eius tenetur. Tempora laboriosam eum et illum voluptas voluptas. Eius facilis in corrupti molestiae.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 178, DateTimeKind.Utc).AddTicks(5083),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 6,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 179, DateTimeKind.Utc).AddTicks(7585),
                            Description = "Asperiores perspiciatis corporis et libero nisi fugit aut atque. Sunt ipsum ratione libero.",
                            Name = "Molestiae velit consequatur cumque repellat quia. Maiores accusantium molestias libero non sint amet doloribus adipisci nihil. In adipisci nemo et enim eaque vero reiciendis sint voluptatibus. Soluta quas aut nisi aperiam et culpa libero autem.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 19m,
                            TechnicalInformation = "Quaerat sint nihil delectus vel. Porro porro quia totam modi reiciendis autem nisi amet. Vel aut dolor aspernatur quod cumque rem reiciendis ut. Voluptatibus mollitia totam eveniet enim explicabo neque quia minus. Et eos atque accusantium magnam. Minus omnis et quo. Amet eius ut omnis dolore aut aut dolorum. Minima quasi ullam dolor ipsum. Ipsam molestiae tempora vero dolorem eos quam id sequi velit. Qui ea beatae eos consequuntur. Fugiat architecto neque blanditiis ipsa commodi iste id ut labore. Adipisci aut nisi iure corporis temporibus assumenda modi voluptatem sint. Similique voluptate quos molestiae qui qui voluptatem autem repudiandae tempora.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 179, DateTimeKind.Utc).AddTicks(7586),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 8,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 180, DateTimeKind.Utc).AddTicks(6235),
                            Description = "Voluptas reprehenderit non cupiditate vitae.",
                            Name = "Sit qui qui a.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 17m,
                            TechnicalInformation = "Non eaque sint voluptatem qui. Repudiandae hic ut sit at labore. Expedita voluptas distinctio nihil eaque neque. Modi minus necessitatibus omnis aperiam voluptatem iusto quia aut. Sunt dicta praesentium itaque facilis distinctio quisquam cupiditate amet sint. Esse aut delectus ut quas et alias. Itaque reiciendis similique dolorem. Molestiae commodi cupiditate qui harum. Tempore est minus cumque minima alias. Ea nobis numquam qui autem necessitatibus. Est sed ea odio dolore est harum sit sed at. Neque quae totam illum itaque minima sed labore harum ut. Voluptatem maiores consequatur at aspernatur sit.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 180, DateTimeKind.Utc).AddTicks(6236),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 181, DateTimeKind.Utc).AddTicks(7381),
                            Description = "Possimus accusantium et molestiae minus voluptate. Et omnis officiis neque excepturi. Corporis inventore aut id accusamus ratione. Non ducimus quam et eius ut numquam.",
                            Name = "Eum enim eius ipsum et distinctio vel magnam soluta et. Quia numquam enim maiores. Dolorum et ratione mollitia et. Voluptatum dolorum tenetur nostrum.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 14m,
                            TechnicalInformation = "Sapiente cupiditate et minus dolores hic excepturi asperiores laudantium. Dignissimos quae officiis qui voluptas quia voluptas neque ipsa amet. Quia dicta rerum nemo perferendis blanditiis. Aut nesciunt facere animi quo excepturi corporis iusto nulla dolore. Ut voluptate quidem ducimus eaque voluptatem placeat. Eveniet voluptates animi quaerat odit. Omnis illum laboriosam omnis tempora omnis error. Voluptatibus tempore sapiente qui. Omnis possimus corrupti eius nobis nam aspernatur. Reprehenderit ipsam veritatis veniam. Ut ut ut quo. Rerum quis magnam optio dolor amet eius ex voluptates.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 181, DateTimeKind.Utc).AddTicks(7382),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 6,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 182, DateTimeKind.Utc).AddTicks(5713),
                            Description = "Sunt quibusdam qui aut. In tempora et mollitia inventore dolores.",
                            Name = "Veniam debitis consequatur cupiditate ipsa inventore temporibus vitae non iure.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 17m,
                            TechnicalInformation = "Nulla iure atque est dolorum itaque quam nulla commodi. Non ipsam molestias dolorum exercitationem sint numquam repellat iste exercitationem. Commodi vitae atque saepe. Eos doloribus magnam vel debitis et dicta. Sequi voluptatem velit porro. Dicta omnis saepe quo voluptatem distinctio eaque assumenda quam. Similique perspiciatis ex aut molestiae iure aut. Et enim qui repellat cupiditate. Sint non qui odio facere aperiam in eum ducimus. Odio repellat autem possimus consequuntur rerum eum natus maxime. Dignissimos eius cupiditate animi qui tenetur facilis.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 182, DateTimeKind.Utc).AddTicks(5713),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 10,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 183, DateTimeKind.Utc).AddTicks(5005),
                            Description = "Sapiente harum fugit ex velit maiores. Quod maxime sit facere eaque ut exercitationem eum dolore.",
                            Name = "Sit provident omnis voluptatem aut neque voluptate. Non voluptatem sit alias vitae. Ut fugiat unde ab perferendis beatae cumque.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 19m,
                            TechnicalInformation = "Nobis voluptatem a ut. Debitis sit accusantium similique beatae omnis aut quo. Perspiciatis natus odit quia aut molestiae dolores. Perferendis similique voluptas voluptate architecto ipsam. Id dolores et qui numquam ab. Alias voluptatem natus non dolores aut. Nihil sit nihil sed voluptatem aut et. Ullam velit rerum sed placeat. Consectetur et dignissimos a necessitatibus commodi sunt quidem quia. Asperiores dolorem aut ullam. Voluptatum eum nemo vero consequatur. Pariatur alias dolor eaque hic beatae expedita cum magni vel. Ab repudiandae blanditiis assumenda quia.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 183, DateTimeKind.Utc).AddTicks(5006),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 184, DateTimeKind.Utc).AddTicks(5132),
                            Description = "Iste excepturi quas provident. At quo et aut corrupti quia expedita quibusdam modi. Et et reiciendis modi. Adipisci incidunt eligendi numquam quia.",
                            Name = "Voluptatem assumenda quia deserunt accusamus voluptas fuga maiores sunt eum. Ipsa ullam suscipit perferendis.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 18m,
                            TechnicalInformation = "Maxime facilis libero architecto quas ut mollitia dicta voluptas est. Magnam voluptatum praesentium ullam accusamus sapiente beatae aperiam molestias corrupti. Sint sit nostrum maxime sed a autem. Ad culpa eum sequi facilis eveniet. Est autem provident ut iusto. Quo quod enim error. Dolorem sequi blanditiis nemo corporis aut. Quo cupiditate exercitationem voluptatibus mollitia earum aut commodi molestias. Voluptatum voluptatibus aut aut illo optio libero consectetur iusto sit. Aut unde aliquam esse commodi quas qui odio. Voluptate maxime maxime hic amet molestias eligendi facilis. Adipisci sed rem consequatur. Inventore dolor qui ipsum culpa sapiente similique.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 184, DateTimeKind.Utc).AddTicks(5133),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 6,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 185, DateTimeKind.Utc).AddTicks(6370),
                            Description = "In qui voluptate molestias architecto recusandae hic quia quia. Voluptas incidunt et dolorem laborum sit nulla quidem laboriosam unde. Distinctio deserunt eligendi fugit. Delectus aut tempora et doloremque.",
                            Name = "Magnam sunt debitis neque. Esse deleniti voluptate deleniti ut dolorem omnis magnam illo placeat. Occaecati velit occaecati et id. Ut eveniet consequatur delectus saepe et.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 13m,
                            TechnicalInformation = "Laborum minima facere qui repellendus eum beatae placeat sed tenetur. Quisquam doloremque inventore recusandae aperiam. Ea voluptas facilis nisi saepe. Dicta dolor suscipit earum quibusdam ratione. Dolores voluptas voluptas et. Natus dignissimos similique quis dignissimos repellendus accusamus. Animi sed repellendus ex officiis tenetur. Tenetur ipsam molestias sed maxime accusamus laboriosam. Excepturi perferendis harum sit assumenda quo blanditiis. Amet porro quisquam aut nam quibusdam porro voluptate unde asperiores. Vel sint cupiditate provident consequatur aut cum omnis. Aliquam ut nam sed enim magnam. Libero ad blanditiis neque deserunt quis aut ut similique.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 185, DateTimeKind.Utc).AddTicks(6370),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 186, DateTimeKind.Utc).AddTicks(3656),
                            Description = "Eum reprehenderit dolore sed voluptatum nihil nesciunt voluptas. Debitis et consequuntur eum qui aperiam necessitatibus.",
                            Name = "Blanditiis veniam sit sapiente aut.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 12m,
                            TechnicalInformation = "Voluptatem suscipit eum sit tempore qui impedit repellat hic. Aliquam fugit iure architecto veniam qui. Aliquam praesentium vel saepe. Repellat minus asperiores sequi perferendis. Architecto et sunt qui consectetur et tempora dolorem eveniet. Alias eos quam quia vel est dolorum praesentium architecto. Dolor aut laborum totam. Reiciendis suscipit asperiores tempora earum. Labore sint id eveniet odio et. Voluptatem quia labore autem odio fugiat autem. Enim asperiores similique autem accusamus at aut rerum corrupti consectetur.",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 186, DateTimeKind.Utc).AddTicks(3656),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1925, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 172, DateTimeKind.Utc).AddTicks(742),
                            Email = "filomena.rowe@langworth.name",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "jaleel_pfannerstill",
                            Name = "Adela",
                            Password = "Sed aut autem et quia at. Accusantium at aut animi saepe voluptas qui. Similique quas occaecati quaerat totam. Dolor ex consectetur dolor architecto.",
                            Phone = "3327509069",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Hammes",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 172, DateTimeKind.Utc).AddTicks(742)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1916, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 172, DateTimeKind.Utc).AddTicks(5931),
                            Email = "raheem@wildermanroob.ca",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "murray",
                            Name = "Taryn",
                            Password = "Eaque labore officiis id sapiente architecto in excepturi est laboriosam. Est est animi delectus aut qui ipsa et. Delectus incidunt corporis consequuntur hic rerum at laborum ad quasi.",
                            Phone = "9412298404",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Stokes",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 172, DateTimeKind.Utc).AddTicks(5931)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1975, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 173, DateTimeKind.Utc).AddTicks(135),
                            Email = "ken@jones.biz",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "malika",
                            Name = "Scot",
                            Password = "Maiores repudiandae praesentium delectus vel et quo nam aut.",
                            Phone = "9193680910",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Littel",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 173, DateTimeKind.Utc).AddTicks(135)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1962, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 173, DateTimeKind.Utc).AddTicks(5939),
                            Email = "ernestine_rempel@eichmann.ca",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "anne.roob",
                            Name = "Jedediah",
                            Password = "Eius quia soluta id dolore sit aut dignissimos magnam. Quaerat qui iusto aut ut autem nostrum. Dolor alias nesciunt sit hic autem ipsum. Vero quaerat accusantium et ea provident ut natus.",
                            Phone = "2755253193",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Padberg",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 173, DateTimeKind.Utc).AddTicks(5939)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1989, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 174, DateTimeKind.Utc).AddTicks(920),
                            Email = "carmelo@gerlach.info",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "ernesto_hauck",
                            Name = "Llewellyn",
                            Password = "Sit voluptates totam commodi asperiores voluptas. Dignissimos quia similique est. Earum praesentium dolor libero laboriosam et dolore molestias sit nemo.",
                            Phone = "3849108155",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Kuvalis",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 174, DateTimeKind.Utc).AddTicks(920)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1920, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 174, DateTimeKind.Utc).AddTicks(5487),
                            Email = "karolann.labadie@hoegerdibbert.us",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "alexane_stiedemann",
                            Name = "Antonio",
                            Password = "Laborum debitis laboriosam accusantium quidem enim ipsa possimus at quo. Hic sed quia nostrum.",
                            Phone = "3680532431",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Hyatt",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 174, DateTimeKind.Utc).AddTicks(5487)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1976, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 175, DateTimeKind.Utc).AddTicks(552),
                            Email = "alfredo_bahringer@kreigerwalsh.com",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "derick",
                            Name = "Terry",
                            Password = "Ipsum delectus aut laboriosam id ipsum culpa.",
                            Phone = "2811251987",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Blanda",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 175, DateTimeKind.Utc).AddTicks(552)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1995, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 175, DateTimeKind.Utc).AddTicks(7140),
                            Email = "hans@nicolas.us",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "jailyn_pouros",
                            Name = "Bridget",
                            Password = "Excepturi animi quos consequuntur. Dolorem sint at necessitatibus. Saepe nesciunt rerum fugit repellat exercitationem quia velit et. Qui voluptatum dignissimos commodi sed et et ullam laborum atque.",
                            Phone = "3379684333",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Parker",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 175, DateTimeKind.Utc).AddTicks(7141)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1918, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 176, DateTimeKind.Utc).AddTicks(1119),
                            Email = "jeanette_harber@hoeger.co.uk",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "cristian",
                            Name = "Obie",
                            Password = "Et sequi qui quibusdam enim sit et ex.",
                            Phone = "3872855697",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Kiehn",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 176, DateTimeKind.Utc).AddTicks(1119)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1960, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 176, DateTimeKind.Utc).AddTicks(6697),
                            Email = "jazlyn@osinskifarrell.co.uk",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "madisyn_mueller",
                            Name = "Ed",
                            Password = "Doloremque harum dolores incidunt et est dolor architecto. Corporis beatae accusamus iusto amet fugiat cum beatae. Sapiente qui placeat et nihil voluptatum qui. Laudantium quia dolore fugiat id qui consequatur.",
                            Phone = "2715806175",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Gerhold",
                            UpdatedAt = new DateTime(2023, 5, 21, 4, 57, 16, 176, DateTimeKind.Utc).AddTicks(6698)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
