// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230618154205_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("price");

                    b.Property<string>("TechnicalInformation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("technical_information");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 6,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6434),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Deanna",
                            Price = 1.988099522783361m,
                            TechnicalInformation = "Earum ea aliquid deleniti accusamus sequi ut illo similique. Et atque fugiat quia totam dolore et perferendis aut. Qui voluptatibus libero saepe architecto corrupti voluptas. Nostrum magni nemo vitae qui est accusantium porro illum. Est qui qui velit molestiae.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6435),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6459),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Deanna",
                            Price = 1.177022583861148m,
                            TechnicalInformation = "fuga",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6459),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6482),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Deanna",
                            Price = 1.676165948677159m,
                            TechnicalInformation = "Fuga illum atque sit ea.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6483),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6508),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Deanna",
                            Price = 1.376438184279359m,
                            TechnicalInformation = "Rerum voluptatem quae est ut voluptas.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6508),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6538),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Deanna",
                            Price = 1.443971368225496m,
                            TechnicalInformation = "Voluptatem aspernatur corrupti aut ipsum iste dicta.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6538),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 4,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6549),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Deanna",
                            Price = 1.429145013612126m,
                            TechnicalInformation = "sequi",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6549),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 2,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6574),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Deanna",
                            Price = 1.654643618590128m,
                            TechnicalInformation = "Eos dolorum et dolore et.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6575),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6716),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Deanna",
                            Price = 1.779066940390644m,
                            TechnicalInformation = "Eveniet similique eos perferendis dignissimos aperiam dolorem. Fugiat maiores aliquam rerum distinctio. Placeat sequi suscipit. Cupiditate libero aliquam numquam vero quo maxime facere et necessitatibus. Excepturi facilis aut quasi ducimus. Unde voluptas ex est delectus.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6716),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 4,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6725),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Deanna",
                            Price = 1.547114873070443m,
                            TechnicalInformation = "nihil",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6725),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 3,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6904),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Deanna",
                            Price = 1.771536607941811m,
                            TechnicalInformation = "Molestias autem consectetur aut sunt libero quam alias. Repudiandae voluptas velit aut. Voluptates architecto qui. Tenetur harum molestiae quas eum neque sapiente.",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(6904),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("NewName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("new_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("path");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_photos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(3578),
                            Name = "Mandatory.jpg",
                            NewName = "real-time.gif",
                            Path = "/platforms",
                            ProductId = 1,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(3579)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(3669),
                            Name = "bus.png",
                            NewName = "orange.png",
                            Path = "/parsing/syndicate/luxembourg",
                            ProductId = 2,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(3669)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4373),
                            Name = "program.png",
                            NewName = "Avon.png",
                            Path = "/integrate",
                            ProductId = 3,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4373)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4734),
                            Name = "Unbranded Granite Fish.png",
                            NewName = "Unions.gif",
                            Path = "/well/deposit",
                            ProductId = 4,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4734)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4784),
                            Name = "envisioneer.jpg",
                            NewName = "Rustic Soft Tuna.gif",
                            Path = "/burgs",
                            ProductId = 5,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(4784)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5582),
                            Name = "RAM.png",
                            NewName = "one-to-one.jpg",
                            Path = "/consultant/internal/gorgeous",
                            ProductId = 6,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5582)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5685),
                            Name = "withdrawal.jpg",
                            NewName = "Grocery & Health.png",
                            Path = "/hacking/e-business/front-line",
                            ProductId = 7,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5685)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5753),
                            Name = "synthesizing.png",
                            NewName = "recontextualize.jpg",
                            Path = "/specialist",
                            ProductId = 8,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5753)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5785),
                            Name = "panel.png",
                            NewName = "sensor.jpg",
                            Path = "/initiative",
                            ProductId = 9,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5786)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5832),
                            Name = "B2B.png",
                            NewName = "Product.jpg",
                            Path = "/union/panama",
                            ProductId = 10,
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 394, DateTimeKind.Utc).AddTicks(5832)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 281, DateTimeKind.Utc).AddTicks(3420),
                            Email = "Sierra82@gmail.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "Kiera.Feeney",
                            Name = "Deanna",
                            Password = "$2a$11$Kg.kcir4TiFfItPZdlCR5.wx0F2/E/ijWUOgaXo1iI9Oug8TFbRFu",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 281, DateTimeKind.Utc).AddTicks(3421)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 405, DateTimeKind.Utc).AddTicks(6288),
                            Email = "Devon.Beier7@gmail.com",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "Caleb.Ratke32",
                            Name = "Deanna",
                            Password = "$2a$11$E8V2SWZDDV5uMkFNBr2nbehp03O0I5MeT0SGKGvyM9haSmcb2/T3m",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 405, DateTimeKind.Utc).AddTicks(6289)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 528, DateTimeKind.Utc).AddTicks(8490),
                            Email = "Ed_Kovacek@gmail.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "Eli_Crist93",
                            Name = "Deanna",
                            Password = "$2a$11$u3FZrOHOfCDSt8PGlK7oy.aNgf1cTfeV7OC6btWpinSyvF63mJCJq",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 528, DateTimeKind.Utc).AddTicks(8491)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 651, DateTimeKind.Utc).AddTicks(8466),
                            Email = "Verna_Bashirian@gmail.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "Marilyne86",
                            Name = "Deanna",
                            Password = "$2a$11$PteAWWpenxK6ZO71eAvkheTlAMClhAehSdofhkl9zblbFFYNaZIQy",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 651, DateTimeKind.Utc).AddTicks(8466)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 775, DateTimeKind.Utc).AddTicks(566),
                            Email = "Amelie84@yahoo.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "Sabryna.Terry20",
                            Name = "Deanna",
                            Password = "$2a$11$ZDA3D1eOO31I3ut3a8HexeyUr0N3Ox/4RyjU1l/XxxoM2R3zYqyqC",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 775, DateTimeKind.Utc).AddTicks(567)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 898, DateTimeKind.Utc).AddTicks(6700),
                            Email = "Buddy9@hotmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "Micah.Ruecker",
                            Name = "Deanna",
                            Password = "$2a$11$CCXm2vpIorP144O4l.CYBuWftXfwP4U1fnKEWAGFXzPQ0UY1l5Aai",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 4, 898, DateTimeKind.Utc).AddTicks(6701)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 21, DateTimeKind.Utc).AddTicks(6628),
                            Email = "Marge38@hotmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "Helen61",
                            Name = "Deanna",
                            Password = "$2a$11$28rHnV9biA3VC35Ij5va2uk8kiHvvbnimxhL4LQAwwwjIk5li5PQ6",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 21, DateTimeKind.Utc).AddTicks(6629)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 145, DateTimeKind.Utc).AddTicks(3673),
                            Email = "Elenora.Klocko96@gmail.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "Jerome_Walsh94",
                            Name = "Deanna",
                            Password = "$2a$11$RjXi5Nn7GUliRcII2gSBZuak.z6.ZR9AjtXoGuhOChb8r71RRvAf2",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 145, DateTimeKind.Utc).AddTicks(3674)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 269, DateTimeKind.Utc).AddTicks(1530),
                            Email = "Filiberto.Schulist@hotmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "Bernice_Abshire",
                            Name = "Deanna",
                            Password = "$2a$11$p3jxvhp13hdfNTBuAkRgWeSyZAIS7Oan4Xes1Aeffqo4FJRNBEslO",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 269, DateTimeKind.Utc).AddTicks(1530)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1975, 4, 8, 8, 5, 23, 350, DateTimeKind.Local).AddTicks(4729),
                            CreatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(928),
                            Email = "Aylin96@yahoo.com",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "Stacy77",
                            Name = "Deanna",
                            Password = "$2a$11$6zjERp..iATU9.4m.Z0YnOXbxf5y3yZurvpl4G7sIRwgz5JPZ7iSS",
                            Phone = "201.616.1610 x9326",
                            Photo = "https://placeimg.com/640/480/any",
                            Surname = "Mann",
                            UpdatedAt = new DateTime(2023, 6, 18, 15, 42, 5, 393, DateTimeKind.Utc).AddTicks(929)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ProductPhoto", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
