// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230514132345_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("TechnicalInformation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("technical_information");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 4,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 246, DateTimeKind.Utc).AddTicks(5422),
                            Description = "Excepturi quasi inventore voluptatibus dolores ipsa magnam. Nisi ducimus ut omnis aperiam.",
                            Name = "Excepturi autem et fuga natus libero et aut. Eum beatae aut illo.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 17m,
                            TechnicalInformation = "Culpa quae sunt voluptatem voluptatem nihil dolor dignissimos eaque sint. Qui ut animi voluptas neque dolore. Est laborum rerum ab et hic quia id et. Ut aut et animi doloremque. Magnam non dolores suscipit. Velit ut esse praesentium qui est cum iusto commodi quam. Incidunt quasi ut dolores aut doloremque aspernatur. Eaque omnis magni cum molestiae pariatur ut accusantium. Ad ipsum sit sit et impedit occaecati maxime itaque. Tempora quia eos inventore. Dolor occaecati eum repellat.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 246, DateTimeKind.Utc).AddTicks(5422),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 247, DateTimeKind.Utc).AddTicks(7844),
                            Description = "Quo suscipit debitis ab.",
                            Name = "Et explicabo aut mollitia ipsum id iusto blanditiis.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 16m,
                            TechnicalInformation = "Consequatur reprehenderit sit eaque possimus animi. Error dolorum repellat consectetur quis aliquid. Laboriosam odit et aliquam dolorem veniam. Maxime est aut enim minus qui quibusdam fugit iusto rerum. Aut dignissimos voluptatem officia eius odit. Nihil voluptatem qui tempora dolore illo cumque. Adipisci amet at laboriosam tempore a. Omnis inventore quibusdam accusamus qui est. Quia temporibus vel quo ut adipisci sit minus nisi. Distinctio animi aperiam animi veniam nostrum est. Magnam enim dolorem debitis optio ut non odio suscipit. Est harum repudiandae dolor quidem itaque. In dolor aperiam numquam porro tempore provident.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 247, DateTimeKind.Utc).AddTicks(7844),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 248, DateTimeKind.Utc).AddTicks(8416),
                            Description = "Quae alias dicta aut voluptatem necessitatibus.",
                            Name = "Vel maiores iusto harum exercitationem aut aut. Possimus fugiat dolorem nobis dolorem accusantium rerum eum.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 13m,
                            TechnicalInformation = "Sit ipsum atque voluptatum sunt. Voluptatem debitis officiis labore. Et quas modi voluptatum ipsam. Reprehenderit esse possimus ex. Totam aliquam qui impedit. Necessitatibus rem facilis et rerum rerum iste nesciunt. Et sed aut sit impedit doloribus. Sapiente nesciunt delectus minus. Optio aperiam neque explicabo cumque. Alias dolorem iste vero aut nemo. Voluptate aspernatur ipsa culpa molestiae rerum officia rerum. Non quis fugit eius perferendis.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 248, DateTimeKind.Utc).AddTicks(8417),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 7,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 249, DateTimeKind.Utc).AddTicks(8479),
                            Description = "Doloribus dolor adipisci officia.",
                            Name = "Voluptatibus dolorem et non voluptatem quae.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 20m,
                            TechnicalInformation = "Voluptas aspernatur suscipit autem dolores quibusdam doloribus libero ducimus. Nesciunt sunt eum tempore dignissimos iure ducimus voluptatem voluptatibus et. Aperiam maiores est reprehenderit. Modi et fugiat non totam dolorum eligendi laborum est consectetur. Molestiae adipisci maxime mollitia. Aut repellendus occaecati est iusto. Sint odio provident omnis fugiat rerum culpa impedit. Consequatur odit dolores excepturi quis. Adipisci alias doloremque magni. Voluptatum aut mollitia asperiores ea temporibus. Aspernatur tenetur nam iure. Vitae consequuntur repudiandae molestiae.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 249, DateTimeKind.Utc).AddTicks(8479),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 251, DateTimeKind.Utc).AddTicks(3876),
                            Description = "Vel ut alias dolores esse cum provident quia expedita ut.",
                            Name = "Veritatis soluta eum et. Ex unde consequatur ab soluta. Est ut enim et nulla iste aut necessitatibus sint. Asperiores molestiae nihil et facilis enim ea.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 12m,
                            TechnicalInformation = "Consequatur eum natus voluptates amet ducimus blanditiis sed. Voluptas vitae ea maxime asperiores. Aut accusantium suscipit expedita quisquam suscipit quis illum velit magnam. Tempora incidunt est modi eaque at. Repudiandae id ut at repellat. Voluptatem voluptas reprehenderit deserunt cupiditate amet alias rerum. Qui delectus ad blanditiis animi sit rerum velit et ut. Assumenda expedita aliquid sapiente mollitia assumenda id et. Reiciendis nam repellat amet at sit a esse. Et provident blanditiis hic sit cumque quis. Sed quod ut voluptatem dolores totam. Excepturi laboriosam in dicta. Quis corrupti sed enim unde consequuntur beatae dolor.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 251, DateTimeKind.Utc).AddTicks(3876),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 7,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 252, DateTimeKind.Utc).AddTicks(7594),
                            Description = "Amet omnis odit sed fugiat voluptate excepturi quae. Rerum et aperiam excepturi quod. Quaerat in et consectetur ducimus mollitia doloremque ut in corrupti.",
                            Name = "Voluptas voluptas architecto vel quia consequatur beatae officia neque. Neque eum omnis totam explicabo non odio facilis. Quia necessitatibus et occaecati voluptates eum consequuntur sapiente a quam.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 18m,
                            TechnicalInformation = "Molestiae nulla aut exercitationem rerum ut. Voluptatem quia nulla facilis sit corporis corrupti. Commodi voluptatem minus aliquid qui sint nihil repellendus aut ipsa. Repellendus est dolor autem magnam minus aspernatur. Vitae voluptatibus voluptate perspiciatis non eos atque. Ratione quo inventore odit est delectus minus. Cupiditate nisi dolores dolores. Aut ab deserunt natus voluptates rerum. Architecto harum aliquam cumque tempora. Voluptatem sunt aliquam rerum.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 252, DateTimeKind.Utc).AddTicks(7594),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 254, DateTimeKind.Utc).AddTicks(2516),
                            Description = "Aperiam delectus dolor quia.",
                            Name = "Eum dolores in mollitia perferendis facere. Voluptas voluptatibus alias dolor assumenda dolor laborum doloribus velit. Vel qui ab expedita minus explicabo. Sint fugiat quia quo nam sit qui reiciendis officiis.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 16m,
                            TechnicalInformation = "Eius magnam tempora quasi. Qui doloribus aspernatur error blanditiis accusantium. Nisi qui quod dolor ex. Adipisci culpa accusantium expedita voluptas non sit illo accusamus ut. Cumque officiis id qui iure omnis. Voluptates voluptates molestiae sunt aliquam. Aut et accusantium magnam facilis sint. Dolores repudiandae mollitia est sint cupiditate deleniti. Aut accusantium tenetur sed ipsam nesciunt ea. Est quisquam nostrum blanditiis rerum rem earum quo aut nihil. Delectus voluptatem earum ea eveniet beatae optio neque illum. Laboriosam et fugit quia vitae itaque. Officia facere nihil impedit aut quam.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 254, DateTimeKind.Utc).AddTicks(2516),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 5,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 256, DateTimeKind.Utc).AddTicks(899),
                            Description = "Non odio itaque et velit omnis vero tenetur. Qui est saepe delectus quia. Accusamus sit voluptas vero aut dolores laborum. Omnis et sunt ut.",
                            Name = "Dicta molestias sed id voluptatem tempora non repellat adipisci expedita. Est eos qui hic quod tempora sint sit consequatur unde. Ex fuga molestiae adipisci odit perferendis itaque non ullam et. Perspiciatis sequi quas fuga amet ipsa.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 12m,
                            TechnicalInformation = "Amet et aut nihil iure eum quasi facere. Nesciunt sit laudantium nostrum ex temporibus sapiente aut sed. A sint et sit et enim et aut esse reiciendis. A qui non quis earum nemo repellendus rerum quam. Voluptatum maxime et eos. Sint perferendis asperiores labore fuga qui. Labore fuga vel praesentium laudantium nesciunt eos eius atque placeat. Ratione voluptatem iste corporis. Assumenda tenetur est adipisci officiis unde sed porro est quisquam. Et laboriosam ullam dolore quis. Libero praesentium est et omnis eveniet et id. Quia consequatur et eaque quia numquam ut et ipsa.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 256, DateTimeKind.Utc).AddTicks(900),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 9,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 257, DateTimeKind.Utc).AddTicks(6671),
                            Description = "Aut eius culpa autem. Consequatur dolorem ea asperiores. A voluptatem hic id quod sit consequuntur ut nulla occaecati.",
                            Name = "Aliquam saepe architecto culpa optio atque. Asperiores consectetur quia est. Non cum qui accusantium. Eum exercitationem distinctio earum.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 20m,
                            TechnicalInformation = "Odit quisquam sunt impedit odio non. Omnis ab quibusdam qui et est fugiat exercitationem repudiandae. Aspernatur distinctio et cumque eos recusandae veniam. Enim perferendis qui ullam officiis repellat et neque eum aliquam. Sunt doloremque et ea numquam placeat provident. Id eius quidem eaque et autem ullam nihil omnis alias. Quis et numquam repellendus possimus. Consequuntur cum dolores nesciunt qui ex minima ea natus dolor. Autem corporis itaque omnis alias doloremque inventore. A ducimus natus cumque in est officia est nihil dolor. Eveniet deserunt quia est aut qui tenetur ut omnis rerum. Quia beatae nihil magni qui.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 257, DateTimeKind.Utc).AddTicks(6672),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1,
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 259, DateTimeKind.Utc).AddTicks(2203),
                            Description = "Voluptas provident non ut voluptates. Corporis et aut eum ipsa. Ea totam doloribus voluptatem hic quasi et voluptatibus et. Et rerum minima quis.",
                            Name = "Facilis harum aperiam soluta animi beatae voluptas in suscipit aliquid. Sit aspernatur vero fuga nisi consequuntur illum tenetur et. Possimus maxime recusandae maiores repudiandae consectetur consequatur et incidunt. Dolores eos maxime libero similique fuga sed quos consequatur.",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Price = 11m,
                            TechnicalInformation = "Et dicta non ut quo sunt est. Rerum illo eius libero. Enim minima occaecati ipsa. Error qui et inventore enim deleniti quod tempore. Qui quia repellendus qui deserunt error. Est hic omnis sed. Autem atque eius voluptates neque explicabo velit. Id eos temporibus commodi similique. Iste et soluta sit aut illum voluptas perspiciatis dolores omnis. Cumque labore aut illum est reiciendis nihil. Ab saepe est qui deleniti.",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 259, DateTimeKind.Utc).AddTicks(2204),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2002, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 237, DateTimeKind.Utc).AddTicks(7966),
                            Email = "sophia@mohrbins.com",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "dorris",
                            Name = "Austin",
                            Password = "Iste ipsa voluptatem et voluptatem impedit. Numquam in incidunt neque sed aut amet. Et ut quo modi quod. Laboriosam optio enim dicta quidem similique vel iure.",
                            Phone = "9210262530",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "O'Conner",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 237, DateTimeKind.Utc).AddTicks(7967)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1966, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 238, DateTimeKind.Utc).AddTicks(5845),
                            Email = "clint@beahan.uk",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "maurice.cummings",
                            Name = "Brant",
                            Password = "Et nihil sunt optio dolorem corporis. Quas et temporibus quasi quia blanditiis. Doloremque dolores quia perferendis. Repudiandae odit alias ut molestiae.",
                            Phone = "0545617278",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Ruecker",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 238, DateTimeKind.Utc).AddTicks(5846)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1905, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 239, DateTimeKind.Utc).AddTicks(5024),
                            Email = "kaley.runolfsdottir@bode.ca",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "allie_treutel",
                            Name = "Ward",
                            Password = "Dolorem a ut exercitationem et non inventore culpa est. Quidem tempora reiciendis sed ut quo. Quia eligendi optio nobis voluptas qui magnam. Corporis in id et numquam eum.",
                            Phone = "3226467077",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Hagenes",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 239, DateTimeKind.Utc).AddTicks(5025)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1914, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 240, DateTimeKind.Utc).AddTicks(4702),
                            Email = "phyllis@wehner.com",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "gay",
                            Name = "Johan",
                            Password = "Voluptatem cum qui consequatur labore minus aliquid ratione quis. Odit quod hic aut et voluptatem laboriosam et eligendi quo. Sed qui ipsum aspernatur enim quam est ex qui. Possimus velit sit necessitatibus maxime rem soluta qui similique.",
                            Phone = "7530483234",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Kihn",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 240, DateTimeKind.Utc).AddTicks(4702)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2015, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 241, DateTimeKind.Utc).AddTicks(3628),
                            Email = "braden@veum.info",
                            IsActive = false,
                            IsAdmin = true,
                            Login = "gilda",
                            Name = "Mike",
                            Password = "Tempora consequatur qui est beatae rerum fuga in officia. Omnis cumque distinctio reiciendis. Dolorem quo voluptatibus deserunt laborum est. Ut ad voluptatibus laudantium et placeat.",
                            Phone = "2969682559",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Donnelly",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 241, DateTimeKind.Utc).AddTicks(3629)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 242, DateTimeKind.Utc).AddTicks(2639),
                            Email = "erica@dickensmonahan.name",
                            IsActive = false,
                            IsAdmin = false,
                            Login = "helga",
                            Name = "Braulio",
                            Password = "Vel consequatur corrupti accusantium eos. Sint dolores consequuntur cum odio ratione. Delectus neque amet asperiores eius. Repellendus et repudiandae itaque nisi similique enim recusandae omnis ducimus.",
                            Phone = "9413328560",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Auer",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 242, DateTimeKind.Utc).AddTicks(2639)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2003, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 243, DateTimeKind.Utc).AddTicks(1617),
                            Email = "leonie.collier@turnervolkman.com",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "miracle",
                            Name = "Bradford",
                            Password = "Quia incidunt deleniti veniam id odio est maxime eius. Ea ad sunt non recusandae modi voluptas at dignissimos ea. Numquam quo facere nostrum aut ipsa exercitationem.",
                            Phone = "4885914051",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Hyatt",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 243, DateTimeKind.Utc).AddTicks(1618)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1989, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 243, DateTimeKind.Utc).AddTicks(7993),
                            Email = "maxime_sporer@schiller.uk",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "iliana_mclaughlin",
                            Name = "Lorine",
                            Password = "Porro odit voluptatem unde sunt.",
                            Phone = "6590124434",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Hegmann",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 243, DateTimeKind.Utc).AddTicks(7993)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1976, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 244, DateTimeKind.Utc).AddTicks(4448),
                            Email = "guido_thompson@willms.us",
                            IsActive = true,
                            IsAdmin = false,
                            Login = "fanny.roberts",
                            Name = "Fausto",
                            Password = "Ut omnis pariatur est explicabo ullam earum sit consectetur.",
                            Phone = "4903312410",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Olson",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 244, DateTimeKind.Utc).AddTicks(4448)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1919, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 245, DateTimeKind.Utc).AddTicks(994),
                            Email = "jean@kuphal.co.uk",
                            IsActive = true,
                            IsAdmin = true,
                            Login = "oswald",
                            Name = "Cierra",
                            Password = "Molestiae a ratione et quis molestias dolor iure reprehenderit occaecati. Aspernatur nam excepturi voluptatem voluptatum eaque velit.",
                            Phone = "4892413186",
                            Photo = "https://loremflickr.com/640/480/abstract",
                            Surname = "Runte",
                            UpdatedAt = new DateTime(2023, 5, 14, 13, 23, 45, 245, DateTimeKind.Utc).AddTicks(994)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
